### ISSUE TITLE
unittest_gtest failed to be imported on python3.3 or above

### ISSUE THREAD

**Issue by naota** [retrieva/pficommon#155]
See below:

```
$ python3.3
Python 3.3.5 (default, Jun 30 2014, 12:20:12) 
[GCC 4.7.3] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> __import__("unittest_gtest")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: source code string cannot contain null bytes
>>> 
$ python3.2
Python 3.2.5 (default, Jul  8 2014, 10:38:55) 
[GCC 4.8.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> __import__("unittest_gtest")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "unittest_gtest.py", line 38, in <module>
    from waflib.TaskGen import before, after, feature
ImportError: No module named waflib.TaskGen
>>> 
```

It seems something changed from python3.3?
e.g. minimal reproducer files foo.py library and loader.py which load foo.py

foo.py:

``` python
def foo():
  pass

# contain null byte <replace with null byte>
```

loader.py:

``` python
import foo
```

and try to execute loader.py with several python versions

```
$ python3.4 loader.py
Traceback (most recent call last):
  File "loader.py", line 1, in <module>
    import foo
TypeError: source code string cannot contain null bytes
$ python3.3 loader.py
Traceback (most recent call last):
  File "loader.py", line 1, in <module>
    import foo
TypeError: source code string cannot contain null bytes
$ python3.2 loader.py
$ python2.7 loader.py
```

**Comment by eiichiroi** [comment]
This problem is fixed in #190, so we can build pficommon in python 2.5-3.5 (maybe - 3.7).

Thank you for reporting an important issue.
